function plot_workspace_matlab(mat_file, data_id)
%PLOT_WORKSPACE_MATLAB Plot translation workspace in a paper-like style.
%   plot_workspace_matlab()
%   plot_workspace_matlab(mat_file)
%   plot_workspace_matlab(mat_file, data_id)
%
% Inputs
%   mat_file : MAT file generated by scripts/gen_workspace.py
%   data_id  : 'all' (default) or numeric mode id such as 1, 2, 3
%
% The script follows the official alphaShape workflow:
%   1) build alphaShape from sampled points
%   2) inspect criticalAlpha(...,'all-points') and criticalAlpha(...,'one-region')
%   3) choose a reachable alpha between the two so concavity is preserved
%   4) approximate unreachable volume as convex hull minus reachable workspace

if nargin < 1 || isempty(mat_file)
    mat_file = fullfile('data', 'workspace_data_csm_cfg_3.4mm_uniform.mat');
end
if nargin < 2 || isempty(data_id)
    data_id = 'all';
end

opts = default_plot_options();
opts.data_id = data_id;

S = load(mat_file);
[pts_raw, field_name] = select_points(S, data_id);
pts_raw = double(pts_raw);
assert(~isempty(pts_raw), 'No workspace points found in "%s".', field_name);

[pts_mm, scale_to_mm] = convert_points_to_mm(pts_raw);
pts_mm = unique(round(pts_mm, 6), 'rows');

[reach_shape, outer_shape, shell, debug_info] = build_workspace_shells(pts_mm, opts);

fig = figure('Color', 'w', 'Name', sprintf('Workspace %s', field_name));
tl = tiledlayout(fig, 1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

ax1 = nexttile(tl, 1);
plot_scene(ax1, pts_mm, shell, opts, false);
title(ax1, workspace_title(field_name), 'FontWeight', 'bold');

ax2 = nexttile(tl, 2);
plot_scene(ax2, pts_mm, shell, opts, true);
title(ax2, 'Side View', 'FontWeight', 'bold');

sgtitle(fig, sprintf('Translation Workspace Visualization (%s)', strrep(field_name, '_', '\_')));

print_debug_info(field_name, pts_raw, pts_mm, scale_to_mm, reach_shape, outer_shape, shell, debug_info);
end

function opts = default_plot_options()
opts.reach_face_color = [0.78, 0.95, 0.76];
opts.reach_face_alpha = 0.38;

opts.unreach_face_color = [0.82, 0.60, 0.42];
opts.unreach_face_alpha = 0.52;

opts.grid_n = 96;
opts.padding_mm = 8;
opts.smooth_passes = 3;
opts.kernel_size = 5;
opts.keep_largest_component = true;

opts.alpha_blend = 0.18;
opts.alpha_scale = 1.03;
opts.show_point_cloud_if_empty = true;

opts.view_az = -38;
opts.view_el = 18;
opts.side_az = 90;
opts.side_el = 0;
end

function [pts, field_name] = select_points(S, data_id)
if isnumeric(data_id)
    field_name = sprintf('mode%d_points', data_id);
elseif isstring(data_id) || ischar(data_id)
    data_id = char(data_id);
    if strcmpi(data_id, 'all')
        field_name = 'all_points';
    elseif startsWith(lower(data_id), 'mode')
        field_name = [data_id '_points'];
    else
        field_name = data_id;
    end
else
    error('Unsupported data_id type.');
end

assert(isfield(S, field_name), 'MAT file does not contain field: %s', field_name);
pts = S.(field_name);
end

function [pts_mm, scale_to_mm] = convert_points_to_mm(pts)
span = max(pts, [], 1) - min(pts, [], 1);
if max(abs(pts(:))) < 1 && max(span) < 1
    scale_to_mm = 1000;
else
    scale_to_mm = 1;
end
pts_mm = pts * scale_to_mm;
end

function [reach_shape, outer_shape, shell, debug_info] = build_workspace_shells(pts, opts)
base_shape = alphaShape(pts(:, 1), pts(:, 2), pts(:, 3));

alpha_all = criticalAlpha(base_shape, 'all-points');
alpha_one = criticalAlpha(base_shape, 'one-region');
alpha_reach = alpha_all + opts.alpha_blend * (alpha_one - alpha_all);
alpha_reach = opts.alpha_scale * alpha_reach;

reach_shape = alphaShape(pts(:, 1), pts(:, 2), pts(:, 3), alpha_reach);
reach_shape.HoleThreshold = 0;
reach_shape.RegionThreshold = 0;

outer_shape = alphaShape(pts(:, 1), pts(:, 2), pts(:, 3), Inf);

reach_regions = numRegions(reach_shape);
if reach_regions > 4
    reach_shape.RegionThreshold = 0.002 * volume(outer_shape);
end

[xmin, xmax, ymin, ymax, zmin, zmax] = padded_bounds(pts, opts.padding_mm);
x = linspace(xmin, xmax, opts.grid_n);
y = linspace(ymin, ymax, opts.grid_n);
z = linspace(zmin, zmax, opts.grid_n);
[X, Y, Z] = meshgrid(x, y, z);

outer_mask = reshape(inShape(outer_shape, X(:), Y(:), Z(:)), size(X));
reach_mask = reshape(inShape(reach_shape, X(:), Y(:), Z(:)), size(X));
unreach_mask = outer_mask & ~reach_mask;

if opts.keep_largest_component
    unreach_mask = keep_largest_6conn_component(unreach_mask);
end

reach_scalar = smooth_binary_volume(double(reach_mask), opts.kernel_size, opts.smooth_passes);
unreach_scalar = smooth_binary_volume(double(unreach_mask), opts.kernel_size, opts.smooth_passes);

fv_reach = isosurface(X, Y, Z, reach_scalar, 0.5);
fv_unreach = isosurface(X, Y, Z, unreach_scalar, 0.5);

shell = struct();
shell.X = X;
shell.Y = Y;
shell.Z = Z;
shell.fv_reach = fv_reach;
shell.fv_unreach = fv_unreach;
shell.grid_size = size(X);
shell.num_outer_voxels = nnz(outer_mask);
shell.num_reach_voxels = nnz(reach_mask);
shell.num_unreachable_voxels = nnz(unreach_mask);

debug_info = struct();
debug_info.alpha_all = alpha_all;
debug_info.alpha_one = alpha_one;
debug_info.alpha_reach = alpha_reach;
debug_info.num_regions = numRegions(reach_shape);
debug_info.reach_volume = volume(reach_shape);
debug_info.outer_volume = volume(outer_shape);
debug_info.outer_minus_reach_volume = max(0, debug_info.outer_volume - debug_info.reach_volume);
debug_info.bounds_mm = [xmin xmax; ymin ymax; zmin zmax];
end

function [xmin, xmax, ymin, ymax, zmin, zmax] = padded_bounds(pts, padding_mm)
mins = min(pts, [], 1) - padding_mm;
maxs = max(pts, [], 1) + padding_mm;

xmin = mins(1); xmax = maxs(1);
ymin = mins(2); ymax = maxs(2);
zmin = mins(3); zmax = maxs(3);
end

function vol = smooth_binary_volume(vol, kernel_size, passes)
kernel = ones(kernel_size, kernel_size, kernel_size);
kernel = kernel / sum(kernel(:));
for i = 1:passes
    vol = convn(vol, kernel, 'same');
end
end

function mask = keep_largest_6conn_component(mask)
sz = size(mask);
visited = false(sz);
active_count = nnz(mask);
best_idx = [];
best_count = 0;

if active_count == 0
    return;
end

for linear_idx = 1:numel(mask)
    if ~mask(linear_idx) || visited(linear_idx)
        continue;
    end

    queue = zeros(active_count, 1);
    head = 1;
    tail = 1;
    queue(1) = linear_idx;
    visited(linear_idx) = true;

    component = zeros(active_count, 1);
    comp_count = 0;

    while head <= tail
        current = queue(head);
        head = head + 1;
        comp_count = comp_count + 1;
        component(comp_count) = current;

        [i, j, k] = ind2sub(sz, current);
        neighbors = [
            i - 1, j, k;
            i + 1, j, k;
            i, j - 1, k;
            i, j + 1, k;
            i, j, k - 1;
            i, j, k + 1
        ];

        for n = 1:6
            ii = neighbors(n, 1);
            jj = neighbors(n, 2);
            kk = neighbors(n, 3);
            if ii < 1 || ii > sz(1) || jj < 1 || jj > sz(2) || kk < 1 || kk > sz(3)
                continue;
            end

            idx = sub2ind(sz, ii, jj, kk);
            if mask(idx) && ~visited(idx)
                tail = tail + 1;
                queue(tail) = idx;
                visited(idx) = true;
            end
        end
    end

    if comp_count > best_count
        best_count = comp_count;
        best_idx = component(1:comp_count);
    end
end

mask = false(sz);
if ~isempty(best_idx)
    mask(best_idx) = true;
end
end

function plot_scene(ax, pts, shell, opts, side_view)
hold(ax, 'on');

if ~isempty(shell.fv_reach.vertices)
    patch(ax, shell.fv_reach, ...
        'FaceColor', opts.reach_face_color, ...
        'EdgeColor', 'none', ...
        'FaceAlpha', opts.reach_face_alpha, ...
        'AmbientStrength', 0.35, ...
        'DiffuseStrength', 0.75, ...
        'SpecularStrength', 0.10);
end

if ~isempty(shell.fv_unreach.vertices)
    patch(ax, shell.fv_unreach, ...
        'FaceColor', opts.unreach_face_color, ...
        'EdgeColor', 'none', ...
        'FaceAlpha', opts.unreach_face_alpha, ...
        'AmbientStrength', 0.30, ...
        'DiffuseStrength', 0.70, ...
        'SpecularStrength', 0.08);
end

if opts.show_point_cloud_if_empty && isempty(shell.fv_reach.vertices)
    scatter3(ax, pts(:, 1), pts(:, 2), pts(:, 3), 3, [0.10 0.45 0.85], 'filled');
end

axis(ax, 'equal');
grid(ax, 'on');
box(ax, 'on');
xlabel(ax, 'X Axis (mm)', 'FontWeight', 'bold');
ylabel(ax, 'Y Axis (mm)', 'FontWeight', 'bold');
zlabel(ax, 'Z Axis (mm)', 'FontWeight', 'bold');
set(ax, 'FontName', 'Times New Roman', 'FontSize', 11, 'LineWidth', 1.0);

lims = compute_equal_limits(pts, opts.padding_mm);
xlim(ax, lims(1:2));
ylim(ax, lims(3:4));
zlim(ax, lims(5:6));

camlight(ax, 'headlight');
camlight(ax, 'right');
lighting(ax, 'gouraud');

if side_view
    view(ax, opts.side_az, opts.side_el);
else
    view(ax, opts.view_az, opts.view_el);
end
end

function lims = compute_equal_limits(pts, padding_mm)
mins = min(pts, [], 1);
maxs = max(pts, [], 1);
center = 0.5 * (mins + maxs);
half_range = 0.5 * max(maxs - mins) + padding_mm;

lims = [
    center(1) - half_range, center(1) + half_range, ...
    center(2) - half_range, center(2) + half_range, ...
    center(3) - half_range, center(3) + half_range
];
end

function text_out = workspace_title(field_name)
if strcmp(field_name, 'all_points')
    text_out = 'Translation Workspace';
else
    text_out = strrep(strrep(field_name, '_points', ''), '_', ' ');
    text_out(1) = upper(text_out(1));
end
end

function print_debug_info(field_name, pts_raw, pts_mm, scale_to_mm, reach_shape, outer_shape, shell, debug_info)
raw_min = min(pts_raw, [], 1);
raw_max = max(pts_raw, [], 1);
mm_min = min(pts_mm, [], 1);
mm_max = max(pts_mm, [], 1);

fprintf('Selected field           : %s\n', field_name);
fprintf('Loaded points            : %d\n', size(pts_mm, 1));
fprintf('Unit scale to mm         : x%d\n', scale_to_mm);
fprintf('Raw min/max              : [%g %g %g] / [%g %g %g]\n', raw_min, raw_max);
fprintf('MM min/max               : [%g %g %g] / [%g %g %g]\n', mm_min, mm_max);
fprintf('MM span                  : [%g %g %g]\n', mm_max - mm_min);
fprintf('criticalAlpha all-points : %.6f mm\n', debug_info.alpha_all);
fprintf('criticalAlpha one-region : %.6f mm\n', debug_info.alpha_one);
fprintf('Chosen reachable alpha   : %.6f mm\n', debug_info.alpha_reach);
fprintf('Reachable numRegions     : %d\n', debug_info.num_regions);
fprintf('Reachable volume         : %.3f mm^3\n', debug_info.reach_volume);
fprintf('Outer hull volume        : %.3f mm^3\n', debug_info.outer_volume);
fprintf('Outer - reach volume     : %.3f mm^3\n', debug_info.outer_minus_reach_volume);
fprintf('Voxel grid size          : %d x %d x %d\n', shell.grid_size);
fprintf('Outer voxels             : %d\n', shell.num_outer_voxels);
fprintf('Reachable voxels         : %d\n', shell.num_reach_voxels);
fprintf('Unreachable voxels       : %d\n', shell.num_unreachable_voxels);
fprintf('alphaShape reach Alpha   : %.6f mm\n', reach_shape.Alpha);
fprintf('alphaShape outer Alpha   : %s\n', 'Inf');
end
