function plot_workspace_matlab(mat_path, render_mode, separate_plots)
% Plot workspace data generated by scripts/gen_workspace.py.
% Example:
%   plot_workspace_matlab('../data/workspace_data_csm_cfg_3.4mm_uniform.mat')
%   plot_workspace_matlab('../data/workspace_data_csm_cfg_3.4mm_uniform.mat', 'convhull', true)

if nargin < 1 || isempty(mat_path)
    mat_path = fullfile('..', 'data', 'workspace_data_csm_cfg_3.4mm_uniform.mat');
end
if nargin < 2 || isempty(render_mode)
    render_mode = 'convhull';
end
if nargin < 3 || isempty(separate_plots)
    separate_plots = true;
end

data = load(mat_path);
mode_colors = [
    228, 26, 28;
    242, 223, 149;
    154, 205, 229;
    199, 199, 199
] / 255.0;
mode_labels = {'C1', 'C2', 'C3', 'C4'};
surface_alpha = 0.35;

fprintf('Loaded MATLAB workspace file: %s\n', mat_path);
for mode = 1:4
    pts = data.(sprintf('mode%d_points', mode));
    fprintf('Mode %d: %d points\n', mode, size(pts, 1));
end

all_pts = [];
for mode = 1:4
    pts = data.(sprintf('mode%d_points', mode));
    if ~isempty(pts)
        all_pts = [all_pts; pts]; %#ok<AGROW>
    end
end

if isempty(all_pts)
    error('No workspace points found in %s.', mat_path);
end

mins = min(all_pts, [], 1);
maxs = max(all_pts, [], 1);
center = (mins + maxs) / 2;
half_range = max(maxs - mins) * 1.1 / 2;

if separate_plots
    figure('Color', 'w', 'Name', 'Workspace');
    tiledlayout(2, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
    for mode = 1:4
        nexttile;
        pts = data.(sprintf('mode%d_points', mode));
        if ~isempty(pts)
            draw_mode_surface(pts, mode_colors(mode, :), surface_alpha, render_mode);
        end
        title(mode_labels{mode});
        axis equal;
        grid on;
        xlabel('X');
        ylabel('Y');
        zlabel('Z');
        xlim(center(1) + [-half_range, half_range]);
        ylim(center(2) + [-half_range, half_range]);
        zlim(center(3) + [-half_range, half_range]);
        view(3);
    end
else
    figure('Color', 'w', 'Name', 'Workspace');
    hold on;
    for mode = 1:4
        pts = data.(sprintf('mode%d_points', mode));
        if ~isempty(pts)
            draw_mode_surface(pts, mode_colors(mode, :), surface_alpha, render_mode);
        end
    end
    axis equal;
    grid on;
    xlabel('X');
    ylabel('Y');
    zlabel('Z');
    xlim(center(1) + [-half_range, half_range]);
    ylim(center(2) + [-half_range, half_range]);
    zlim(center(3) + [-half_range, half_range]);
    legend(mode_labels, 'Location', 'northeast');
    view(3);
end
end

function draw_mode_surface(points, color, face_alpha, render_mode)
points = unique(round(points, 9), 'rows');
if size(points, 1) < 4
    scatter3(points(:, 1), points(:, 2), points(:, 3), 8, 'MarkerFaceColor', color, ...
        'MarkerEdgeColor', 'none', 'MarkerFaceAlpha', face_alpha);
    return;
end

switch lower(render_mode)
    case 'convhull'
        tri = convhull(points(:, 1), points(:, 2), points(:, 3), 'Simplify', true);
        trisurf(tri, points(:, 1), points(:, 2), points(:, 3), ...
            'FaceColor', color, 'FaceAlpha', face_alpha, 'EdgeColor', 'none');
    case 'scatter'
        scatter3(points(:, 1), points(:, 2), points(:, 3), 3, ...
            'MarkerEdgeColor', 'none', 'MarkerFaceColor', color, 'MarkerFaceAlpha', 0.04);
    otherwise
        error('Unsupported render_mode: %s. Use convhull or scatter.', render_mode);
end
end
